from __future__ import annotations

"""Layout constants for the NomadCast Tk UI."""

PAD_SM = 4
PAD = 8
PAD_LG = 12
PAD_XL = 16
PAD_2XL = 24

WINDOW_PADDING = PAD_2XL
HEADER_PAD_Y = (0, PAD_LG)
SUBTITLE_PAD_Y = (0, PAD_XL)
ENTRY_PAD_Y = (0, PAD_XL)
BUTTON_ROW_PAD_Y = (0, PAD_XL)
BUTTON_SPACING_X = (PAD_LG, 0)
STATUS_PAD_Y = (0, 0)
FUTURE_ROW_PAD_Y = (PAD, 0)
COMING_SOON_PAD_Y = (PAD_XL, 0)
SUBTITLE_WRAP = 640
